stages:
  - production

deploy:
  stage: production
  when: manual
  tags:
    - hack
  only:
    - main
  script:
    - docker build -t backend-image .
    - docker stop backend-container || true && docker rm backend-container || true
    - docker run -d --name backend-container -p 3000:3000 backend-image
