export const COLOR_PRIMARY = 'primary'
export const COLOR_SUCCESS = 'success'
export const COLOR_WARNING = 'warning'
export const COLOR_DANGER = 'danger'
export const COLOR_DEFAULT = 'default'
export const COLOR_SUBDUED = 'subdued'

export const BACKGROUND_SUBDUED = '#b4b4b4'
export const BACKGROUND_DEFAULT = '#343741'
export const BACKGROUND_PRIMARY = '#0077CC'
export const BACKGROUND_ACCENT = '#017D73'
export const BACKGROUND_SUCCESS = '#007871'
export const BACKGROUND_WARNING = '#FEC514'
export const BACKGROUND_DANGER = '#BD271E'
export const BACKGROUND_LIGHT = '#FFFFFF'
export const BACKGROUND_LIGHTEST = '#F5F7FA'
export const BACKGROUND_DARK = '#1D1E23'
export const BACKGROUND_DARKEST = '#141519'

export const TEXT_DEFAULT = '#343741'
export const TEXT_SUBDUED = '#646A77'
export const TEXT_PRIMARY = '#006BB8'
export const TEXT_ACCENT = '#017D73'
export const TEXT_SUCCESS = '#007871'
export const TEXT_WARNING = '#83650A'
export const TEXT_DANGER = '#BD271E'
export const TEXT_LIGHT = '#DFE5EF'
export const TEXT_DARK = '#343741'
